// scripts/depth-audit/report.ts
import { DIMENSIONS } from "./types";
import type { UnitScore } from "./aggregate";
import { isFoundation } from "./classify";

interface UnitRow {
  unitKey: string; overall: number; passes: boolean; scored: boolean;
  teachingCount: number; auxiliaryCount: number; worstTeachingLesson: string | null;
  dimMean: Record<string, number>;
}
export interface ScoresJson {
  generatedNote: string;
  bar: number;
  scale: "absolute";
  summary: { spineTotal: number; spinePassing: number; spineFailing: number; noTeachingCount: number; foundationsCount: number };
  spine: UnitRow[];        // scored spine units — gated against the bar
  noTeaching: UnitRow[];   // units with no teaching lessons (e.g. start-here nav) — not gradable
  foundations: UnitRow[];  // scored foundation units — reported, not gated
}

function toRow(s: UnitScore, bar: number): UnitRow {
  return {
    unitKey: s.unitKey, overall: Number(s.overall.toFixed(2)),
    passes: s.scored && s.passes(bar), scored: s.scored,
    teachingCount: s.teachingCount, auxiliaryCount: s.auxiliaryCount,
    worstTeachingLesson: s.worstTeachingLesson,
    dimMean: Object.fromEntries(DIMENSIONS.map((d) => [d, Number(s.dimMean[d].toFixed(2))])),
  };
}

export function buildReport(scores: UnitScore[], bar: number): { json: ScoresJson; markdown: string } {
  const sorted = [...scores].sort((a, b) => a.overall - b.overall); // worst first
  const spine = sorted.filter((s) => !isFoundation(s.unitKey) && s.scored).map((s) => toRow(s, bar));
  const noTeaching = sorted.filter((s) => !s.scored).map((s) => toRow(s, bar));
  const foundations = sorted.filter((s) => isFoundation(s.unitKey) && s.scored).map((s) => toRow(s, bar));
  const spineFailing = spine.filter((u) => !u.passes).length;

  const json: ScoresJson = {
    generatedNote: "Generated by scripts/depth-audit. Do not edit by hand.",
    bar, scale: "absolute",
    summary: {
      spineTotal: spine.length, spinePassing: spine.length - spineFailing,
      spineFailing, noTeachingCount: noTeaching.length, foundationsCount: foundations.length,
    },
    spine, noTeaching, foundations,
  };

  const row = (u: UnitRow) =>
    `| ${u.passes ? "PASS" : "**FAIL**"} | ${u.overall.toFixed(2)} | ${u.unitKey} | ${u.teachingCount} | ${u.auxiliaryCount} | ${u.worstTeachingLesson ?? "—"} |`;
  const table = (rows: UnitRow[]) =>
    [`| status | overall | unit | teaching | aux | worst teaching lesson |`,
     `|--------|---------|------|----------|-----|-----------------------|`,
     ...rows.map(row)].join("\n");

  const markdown = [
    `# Depth audit — report`,
    ``,
    `Absolute bar = **${bar}** (teaching-lesson weighted mean). Spine: ${spineFailing}/${spine.length} units below bar. ` +
      `${noTeaching.length} units have no teaching lessons (not gradable); foundations (${foundations.length}) reported separately, not gated.`,
    ``,
    `## Spine (gated)`,
    table(spine),
    ``,
    `## No teaching content (not gradable — navigation/aux-only units)`,
    table(noTeaching),
    ``,
    `## Foundations (not gated — beginner tracks)`,
    table(foundations),
  ].join("\n");

  return { json, markdown };
}
