import sys
sys.path.insert(0, 'graphify-out')
import relinear_emit as emit

concepts = {
    'relational_model': 'Relational model (Codd)',
    'normalization': 'Normalization (1NF-BCNF)',
    'denormalization': 'Denormalization',
    'surrogate_natural_keys': 'Surrogate vs natural keys',
    'db_constraints': 'Declarative constraints',
    'foreign_keys': 'Foreign keys at scale',
    'postgres_data_types': 'Postgres data types',
    'jsonb_storage': 'JSONB and array storage',
    'heap_toast_storage': 'Heap and TOAST storage',
    'schema_design': 'Schema design discipline',
    'btree_index': 'B-tree index',
    'index_leading_column': 'Index leading-column rule',
    'partial_index': 'Partial index',
    'expression_index': 'Expression index',
    'covering_index': 'Covering / INCLUDE index',
    'gin_gist_brin_index': 'GIN/GiST/BRIN indexes',
    'index_write_cost': 'Index write amplification',
    'hnsw_vector_index': 'HNSW vector index (pgvector)',
    'index_bloat': 'Index bloat and REINDEX',
    'create_index_concurrently': 'CREATE INDEX CONCURRENTLY',
    'query_planner': 'Postgres query planner',
    'explain_analyze': 'EXPLAIN ANALYZE',
    'planner_statistics': 'Planner statistics (pg_statistic)',
    'row_estimate_error': 'Row-estimate errors',
    'join_algorithms': 'Join algorithms',
    'scan_types': 'Scan types (seq/index/bitmap)',
    'extended_statistics': 'Extended statistics (CREATE STATISTICS)',
    'plan_cache': 'Generic vs custom plans',
    'sargability': 'Sargable predicates',
    'cost_model_tuning': 'Cost-constant / SSD tuning',
    'mvcc': 'MVCC multi-version concurrency',
    'snapshot_isolation': 'Snapshot visibility',
    'isolation_levels': 'Isolation levels and anomalies',
    'serializable_ssi': 'Serializable Snapshot Isolation',
    'table_bloat': 'Table bloat',
    'autovacuum': 'Autovacuum',
    'xid_wraparound': 'XID wraparound and freezing',
    'hot_updates': 'HOT updates and fillfactor',
    'connection_pooling': 'Connection pooling',
    'pgbouncer_modes': 'PgBouncer pooling modes',
    'pool_sizing': 'Pool sizing math',
    'pool_exhaustion': 'Pool exhaustion',
    'idle_in_transaction': 'Idle-in-transaction',
    'prepared_statements': 'Prepared statements',
    'schema_migrations': 'Schema migrations',
    'postgres_lock_matrix': 'Postgres lock matrix',
    'lock_queue_failure': 'Lock-queue failure mode',
    'expand_contract': 'Expand-contract migration pattern',
    'lock_timeout': 'lock_timeout discipline',
    'migration_tooling': 'Migration tooling (pgroll/Atlas/Squawk)',
    'sharding': 'Database sharding',
    'shard_key': 'Shard-key selection',
    'hot_shard': 'Hot-shard failure mode',
    'data_colocation': 'Data co-location',
    'citus': 'Citus distributed Postgres',
    'declarative_partitioning': 'Declarative partitioning',
    'cross_shard_query': 'Cross-shard queries',
    'online_resharding': 'Online resharding',
    'two_phase_commit': 'Distributed transactions / 2PC',
    'cdc_change_data_capture': 'Change data capture (CDC)',
    'read_replica_lag': 'Read-replica lag',
    'capacity_planning': 'Capacity planning',
    'scale_tiers': 'Scale-tier progression',
    'database_observability': 'Database observability (pg_stat_statements)',
    'red_use_method': 'RED/USE method metrics',
}

piece_concepts = {
    '01-relational-model': ['relational_model', 'normalization', 'denormalization',
        'surrogate_natural_keys', 'db_constraints', 'foreign_keys',
        'postgres_data_types', 'jsonb_storage', 'heap_toast_storage', 'schema_design'],
    '02-indexes': ['btree_index', 'index_leading_column', 'partial_index',
        'expression_index', 'covering_index', 'gin_gist_brin_index',
        'index_write_cost', 'hnsw_vector_index', 'index_bloat',
        'create_index_concurrently'],
    '03-execution-plans': ['query_planner', 'explain_analyze', 'planner_statistics',
        'row_estimate_error', 'join_algorithms', 'scan_types', 'extended_statistics',
        'plan_cache', 'sargability', 'cost_model_tuning'],
    '04-mvcc-isolation': ['mvcc', 'snapshot_isolation', 'isolation_levels',
        'serializable_ssi', 'table_bloat', 'autovacuum', 'xid_wraparound',
        'hot_updates'],
    '05-pooling': ['connection_pooling', 'pgbouncer_modes', 'pool_sizing',
        'pool_exhaustion', 'idle_in_transaction', 'prepared_statements'],
    '06-migrations': ['schema_migrations', 'postgres_lock_matrix', 'lock_queue_failure',
        'expand_contract', 'create_index_concurrently', 'lock_timeout',
        'migration_tooling'],
    '07-sharding': ['sharding', 'shard_key', 'hot_shard', 'data_colocation', 'citus',
        'declarative_partitioning', 'cross_shard_query', 'online_resharding',
        'two_phase_commit', 'cdc_change_data_capture'],
    '08-putting-it-together': ['scale_tiers', 'capacity_planning', 'read_replica_lag',
        'database_observability', 'red_use_method', 'mvcc', 'sharding', 'query_planner',
        'schema_migrations', 'connection_pooling'],
}

R = 'conceptually_related_to'
S = 'semantically_similar_to'
relations = [
    ('relational_model', 'normalization', R, 0.95),
    ('normalization', 'denormalization', R, 0.95),
    ('relational_model', 'db_constraints', R, 0.85),
    ('db_constraints', 'foreign_keys', R, 0.95),
    ('jsonb_storage', 'heap_toast_storage', R, 0.85),
    ('postgres_data_types', 'schema_design', R, 0.85),
    ('schema_design', 'schema_migrations', R, 0.85),
    ('btree_index', 'index_leading_column', R, 0.95),
    ('btree_index', 'gin_gist_brin_index', R, 0.85),
    ('partial_index', 'expression_index', R, 0.85),
    ('covering_index', 'btree_index', R, 0.85),
    ('index_write_cost', 'hot_updates', R, 0.75),
    ('index_bloat', 'table_bloat', S, 0.85),
    ('create_index_concurrently', 'lock_queue_failure', R, 0.85),
    ('btree_index', 'scan_types', R, 0.85),
    ('query_planner', 'explain_analyze', R, 0.95),
    ('query_planner', 'planner_statistics', R, 0.95),
    ('planner_statistics', 'row_estimate_error', R, 0.95),
    ('row_estimate_error', 'extended_statistics', R, 0.85),
    ('query_planner', 'join_algorithms', R, 0.85),
    ('query_planner', 'scan_types', R, 0.85),
    ('sargability', 'index_leading_column', R, 0.75),
    ('plan_cache', 'prepared_statements', R, 0.85),
    ('cost_model_tuning', 'query_planner', R, 0.85),
    ('mvcc', 'snapshot_isolation', R, 0.95),
    ('snapshot_isolation', 'isolation_levels', R, 0.95),
    ('isolation_levels', 'serializable_ssi', R, 0.95),
    ('mvcc', 'table_bloat', R, 0.95),
    ('table_bloat', 'autovacuum', R, 0.95),
    ('autovacuum', 'xid_wraparound', R, 0.85),
    ('mvcc', 'hot_updates', R, 0.85),
    ('connection_pooling', 'pgbouncer_modes', R, 0.95),
    ('pgbouncer_modes', 'prepared_statements', R, 0.85),
    ('pool_sizing', 'pool_exhaustion', R, 0.95),
    ('pool_exhaustion', 'idle_in_transaction', R, 0.85),
    ('idle_in_transaction', 'table_bloat', R, 0.75),
    ('schema_migrations', 'postgres_lock_matrix', R, 0.95),
    ('postgres_lock_matrix', 'lock_queue_failure', R, 0.95),
    ('lock_queue_failure', 'lock_timeout', R, 0.95),
    ('expand_contract', 'schema_migrations', R, 0.95),
    ('migration_tooling', 'schema_migrations', R, 0.85),
    ('sharding', 'shard_key', R, 0.95),
    ('shard_key', 'hot_shard', R, 0.95),
    ('shard_key', 'data_colocation', R, 0.95),
    ('sharding', 'citus', R, 0.95),
    ('citus', 'declarative_partitioning', R, 0.75),
    ('cross_shard_query', 'two_phase_commit', R, 0.85),
    ('online_resharding', 'sharding', R, 0.85),
    ('cdc_change_data_capture', 'cross_shard_query', R, 0.65),
    ('scale_tiers', 'capacity_planning', R, 0.85),
    ('read_replica_lag', 'mvcc', R, 0.65),
    ('database_observability', 'red_use_method', R, 0.85),
    ('database_observability', 'explain_analyze', R, 0.75),
]

emit.emit_chunk('databases', 'databases', concepts, piece_concepts, relations)
