import sys
sys.path.insert(0, 'graphify-out')
import relinear_emit as emit

concepts = {
    'three_pillars': 'Three pillars of observability',
    'metrics_signal': 'Metrics signal',
    'logs_signal': 'Logs signal',
    'traces_signal': 'Traces signal',
    'cardinality_cost': 'Metric cardinality cost',
    'sampling_cost': 'Trace sampling cost',
    'telemetry_join_keys': 'Telemetry join keys',
    'exemplars': 'Exemplars (metric-to-trace bridge)',
    'observability_2_0': 'Observability 2.0 / wide events',
    'opentelemetry': 'OpenTelemetry',
    'structured_logging': 'Structured logging',
    'log_schema': 'Log schema',
    'log_levels': 'Log levels and routing',
    'log_sampling': 'Log sampling',
    'pii_redaction': 'PII redaction at source',
    'log_injection': 'Log injection attack',
    'trace_context_in_logs': 'Trace context in logs',
    'log_retention_tiering': 'Log retention tiering',
    'log_based_metrics': 'Log-based metrics',
    'otel_api_sdk': 'OTel API and SDK',
    'otel_collector': 'OTel Collector',
    'otlp_protocol': 'OTLP wire protocol',
    'semantic_conventions': 'OTel Semantic Conventions',
    'auto_instrumentation': 'Auto-instrumentation',
    'tail_sampling': 'Tail sampling',
    'ebpf_instrumentation': 'eBPF auto-instrumentation',
    'collector_deployment': 'Collector deployment patterns',
    'red_use_method': 'RED/USE method metrics',
    'four_golden_signals': 'Four golden signals',
    'histograms_vs_averages': 'Histograms vs averages',
    'psi_pressure_stall': 'Pressure Stall Information (PSI)',
    'prometheus_instrumentation': 'Prometheus instrumentation',
    'slo': 'Service Level Objective (SLO)',
    'sli': 'Service Level Indicator (SLI)',
    'error_budget': 'Error budgets',
    'burn_rate_alerting': 'Burn-rate alerting',
    'mwmbr_alerting': 'Multi-window multi-burn-rate alerts',
    'error_budget_policy': 'Error budget policy',
    'sla_vs_slo': 'SLA vs SLO',
    'rolling_window': 'Rolling SLO window',
    'distributed_tracing': 'Distributed tracing (W3C Trace Context)',
    'w3c_traceparent': 'W3C traceparent header',
    'trace_baggage': 'Trace baggage propagation',
    'head_tail_sampling': 'Head vs tail sampling',
    'async_context_propagation': 'Async context propagation',
    'span_links': 'Span links',
    'trace_id_join_key': 'Trace-id as join key',
    'b3_propagation': 'B3 vs W3C propagation',
    'profiling': 'Profiling',
    'flame_graph': 'Flame graph',
    'sampling_profiler': 'Sampling profiler',
    'continuous_profiling': 'Continuous profiling',
    'ebpf_profiling': 'eBPF language-agnostic profiling',
    'off_cpu_profiling': 'Off-CPU profiling',
    'memory_allocation_profile': 'Memory / allocation profile',
    'profile_guided_optimization': 'Profile-guided optimization (PGO)',
    'profile_trace_join': 'Joining profiles to traces',
    'observability_debugging_loop': 'SLO-RED-trace-profile debugging loop',
    'mttd_mttr': 'MTTD vs MTTR',
    'blameless_postmortem': 'Blameless postmortem',
    'chaos_engineering': 'Chaos engineering / game days',
    'observability_cost_discipline': 'Observability cost discipline',
}

piece_concepts = {
    '01-three-pillars': ['three_pillars', 'metrics_signal', 'logs_signal',
        'traces_signal', 'cardinality_cost', 'sampling_cost', 'telemetry_join_keys',
        'exemplars', 'observability_2_0', 'opentelemetry'],
    '02-structured-logging': ['structured_logging', 'log_schema', 'log_levels',
        'log_sampling', 'pii_redaction', 'log_injection', 'trace_context_in_logs',
        'log_retention_tiering', 'log_based_metrics'],
    '03-otel': ['opentelemetry', 'otel_api_sdk', 'otel_collector', 'otlp_protocol',
        'semantic_conventions', 'auto_instrumentation', 'tail_sampling',
        'ebpf_instrumentation', 'collector_deployment'],
    '04-red-use': ['red_use_method', 'four_golden_signals', 'cardinality_cost',
        'histograms_vs_averages', 'psi_pressure_stall', 'prometheus_instrumentation'],
    '05-slo-budgets': ['slo', 'sli', 'error_budget', 'burn_rate_alerting',
        'mwmbr_alerting', 'error_budget_policy', 'sla_vs_slo', 'rolling_window'],
    '06-trace-propagation': ['distributed_tracing', 'w3c_traceparent', 'trace_baggage',
        'head_tail_sampling', 'async_context_propagation', 'span_links',
        'trace_id_join_key', 'b3_propagation'],
    '07-profiling': ['profiling', 'flame_graph', 'sampling_profiler',
        'continuous_profiling', 'ebpf_profiling', 'off_cpu_profiling',
        'memory_allocation_profile', 'profile_guided_optimization', 'profile_trace_join'],
    '08-putting-it-together': ['observability_debugging_loop', 'mttd_mttr',
        'blameless_postmortem', 'chaos_engineering', 'observability_cost_discipline',
        'opentelemetry', 'red_use_method', 'slo', 'distributed_tracing', 'profiling'],
}

R = 'conceptually_related_to'
S = 'semantically_similar_to'
relations = [
    ('three_pillars', 'metrics_signal', R, 0.95),
    ('three_pillars', 'logs_signal', R, 0.95),
    ('three_pillars', 'traces_signal', R, 0.95),
    ('metrics_signal', 'cardinality_cost', R, 0.95),
    ('traces_signal', 'sampling_cost', R, 0.95),
    ('telemetry_join_keys', 'trace_id_join_key', S, 0.85),
    ('exemplars', 'metrics_signal', R, 0.75),
    ('observability_2_0', 'three_pillars', R, 0.85),
    ('opentelemetry', 'three_pillars', R, 0.85),
    ('structured_logging', 'log_schema', R, 0.95),
    ('structured_logging', 'logs_signal', R, 0.95),
    ('log_levels', 'log_sampling', R, 0.85),
    ('pii_redaction', 'log_injection', R, 0.75),
    ('trace_context_in_logs', 'distributed_tracing', R, 0.85),
    ('log_based_metrics', 'metrics_signal', R, 0.75),
    ('log_retention_tiering', 'observability_cost_discipline', R, 0.75),
    ('opentelemetry', 'otel_api_sdk', R, 0.95),
    ('opentelemetry', 'otel_collector', R, 0.95),
    ('otel_collector', 'otlp_protocol', R, 0.95),
    ('opentelemetry', 'semantic_conventions', R, 0.85),
    ('auto_instrumentation', 'ebpf_instrumentation', R, 0.85),
    ('otel_collector', 'tail_sampling', R, 0.85),
    ('otel_collector', 'collector_deployment', R, 0.95),
    ('tail_sampling', 'head_tail_sampling', S, 0.95),
    ('red_use_method', 'four_golden_signals', R, 0.95),
    ('red_use_method', 'cardinality_cost', R, 0.85),
    ('red_use_method', 'histograms_vs_averages', R, 0.85),
    ('red_use_method', 'psi_pressure_stall', R, 0.75),
    ('red_use_method', 'prometheus_instrumentation', R, 0.85),
    ('slo', 'sli', R, 0.95),
    ('slo', 'error_budget', R, 0.95),
    ('error_budget', 'burn_rate_alerting', R, 0.95),
    ('burn_rate_alerting', 'mwmbr_alerting', R, 0.95),
    ('error_budget', 'error_budget_policy', R, 0.95),
    ('slo', 'sla_vs_slo', R, 0.85),
    ('error_budget', 'rolling_window', R, 0.85),
    ('slo', 'red_use_method', R, 0.85),
    ('distributed_tracing', 'w3c_traceparent', R, 0.95),
    ('w3c_traceparent', 'trace_baggage', R, 0.95),
    ('distributed_tracing', 'head_tail_sampling', R, 0.85),
    ('async_context_propagation', 'distributed_tracing', R, 0.85),
    ('span_links', 'distributed_tracing', R, 0.85),
    ('w3c_traceparent', 'b3_propagation', R, 0.85),
    ('trace_id_join_key', 'distributed_tracing', R, 0.95),
    ('profiling', 'flame_graph', R, 0.95),
    ('profiling', 'sampling_profiler', R, 0.95),
    ('profiling', 'continuous_profiling', R, 0.95),
    ('continuous_profiling', 'ebpf_profiling', R, 0.85),
    ('profiling', 'off_cpu_profiling', R, 0.85),
    ('profiling', 'memory_allocation_profile', R, 0.85),
    ('profile_trace_join', 'distributed_tracing', R, 0.85),
    ('profile_guided_optimization', 'profiling', R, 0.75),
    ('observability_debugging_loop', 'mttd_mttr', R, 0.95),
    ('observability_debugging_loop', 'slo', R, 0.85),
    ('observability_debugging_loop', 'profiling', R, 0.85),
    ('blameless_postmortem', 'chaos_engineering', R, 0.75),
    ('observability_cost_discipline', 'sampling_cost', R, 0.85),
]

emit.emit_chunk('observability', 'observability', concepts, piece_concepts, relations)
