import sys, json
from pathlib import Path
sys.path.insert(0, 'graphify-out')
import relinear_emit as emit

R = 'conceptually_related_to'
S = 'semantically_similar_to'

# ---- apis / graphql-n-plus-one ----
emit.emit_chunk('apis', 'apis',
    {
        'graphql_resolvers': 'GraphQL resolvers',
        'n_plus_one': 'N+1 query problem',
        'dataloader_batching': 'DataLoader batch loader',
        'per_request_loader_scope': 'Per-request loader scope',
        'apollo_federation': 'Apollo Federation entity resolvers',
        'persisted_queries': 'Persisted / trusted queries',
        'query_complexity_limiting': 'Query complexity scoring',
        'depth_limiting': 'Query depth limiting',
        'alias_bomb_attack': 'Batching / alias-bomb attack',
        'introspection_security': 'GraphQL introspection exposure',
        'graphql_over_http': 'GraphQL-over-HTTP spec',
    },
    {'06-graphql-n-plus-one': ['graphql_resolvers', 'n_plus_one', 'dataloader_batching',
        'per_request_loader_scope', 'apollo_federation', 'persisted_queries',
        'query_complexity_limiting', 'depth_limiting', 'alias_bomb_attack',
        'introspection_security', 'graphql_over_http']},
    [
        ('graphql_resolvers', 'n_plus_one', R, 0.95),
        ('n_plus_one', 'dataloader_batching', R, 0.95),
        ('dataloader_batching', 'per_request_loader_scope', R, 0.95),
        ('apollo_federation', 'n_plus_one', R, 0.85),
        ('persisted_queries', 'introspection_security', R, 0.75),
        ('query_complexity_limiting', 'depth_limiting', R, 0.95),
        ('alias_bomb_attack', 'query_complexity_limiting', R, 0.85),
        ('graphql_over_http', 'persisted_queries', R, 0.75),
    ])

# ---- backend / idempotency-retries ----
emit.emit_chunk('backend', 'backend',
    {
        'idempotency_keys': 'Idempotency keys',
        'exactly_once_processing': 'Effectively-once processing',
        'at_least_once_delivery': 'At-least-once delivery',
        'retry_backoff_jitter': 'Exponential backoff with jitter',
        'retry_storm': 'Retry storms and retry budgets',
        'outbox_pattern': 'Outbox pattern',
        'inbox_pattern': 'Inbox / consumer-dedup pattern',
        'dual_write_problem': 'Dual-write problem',
        'dlq_poison_message': 'Dead-letter queue / poison message',
        'advisory_locks': 'Advisory vs row locks',
        'connection_pooling': 'Connection pooling',
        'idempotency_state_machine': 'Idempotency-key state machine',
    },
    {'05-idempotency-retries': ['idempotency_keys', 'exactly_once_processing',
        'at_least_once_delivery', 'retry_backoff_jitter', 'retry_storm',
        'outbox_pattern', 'inbox_pattern', 'dual_write_problem', 'dlq_poison_message',
        'advisory_locks', 'connection_pooling', 'idempotency_state_machine']},
    [
        ('idempotency_keys', 'idempotency_state_machine', R, 0.95),
        ('idempotency_keys', 'exactly_once_processing', R, 0.95),
        ('at_least_once_delivery', 'exactly_once_processing', R, 0.95),
        ('retry_backoff_jitter', 'retry_storm', R, 0.95),
        ('outbox_pattern', 'dual_write_problem', R, 0.95),
        ('inbox_pattern', 'outbox_pattern', R, 0.85),
        ('dlq_poison_message', 'retry_storm', R, 0.75),
        ('advisory_locks', 'idempotency_state_machine', R, 0.75),
    ])

# ---- caching / stampede ----
emit.emit_chunk('caching', 'caching',
    {
        'cache_stampede': 'Cache stampede / thundering herd',
        'distributed_locking': 'Distributed locking',
        'single_flight': 'Single-flight / request coalescing',
        'probabilistic_early_expiration': 'Probabilistic early expiration (XFetch)',
        'stale_while_revalidate': 'stale-while-revalidate',
        'cache_aside_patterns': 'Cache-aside / read-through / write-through',
        'negative_caching': 'Negative caching and miss-storms',
        'memcache_leases': 'Facebook memcache leases',
        'cache_priming': 'Pre-warming / cache priming',
        'metastable_failure': 'Metastable failure',
    },
    {'03-stampede': ['cache_stampede', 'distributed_locking', 'single_flight',
        'probabilistic_early_expiration', 'stale_while_revalidate',
        'cache_aside_patterns', 'negative_caching', 'memcache_leases',
        'cache_priming', 'metastable_failure']},
    [
        ('cache_stampede', 'distributed_locking', R, 0.95),
        ('cache_stampede', 'single_flight', R, 0.95),
        ('cache_stampede', 'probabilistic_early_expiration', R, 0.95),
        ('cache_stampede', 'stale_while_revalidate', R, 0.95),
        ('single_flight', 'memcache_leases', R, 0.85),
        ('cache_aside_patterns', 'cache_stampede', R, 0.85),
        ('negative_caching', 'cache_stampede', R, 0.85),
        ('cache_stampede', 'metastable_failure', R, 0.85),
        ('cache_priming', 'cache_stampede', R, 0.75),
    ])

# ---- distributed / raft ----
emit.emit_chunk('distributed', 'distributed',
    {
        'raft_consensus': 'Raft consensus',
        'leader_election': 'Leader election and terms',
        'replicated_log': 'Replicated log and AppendEntries',
        'quorum_majority': 'Majority quorum',
        'joint_consensus': 'Joint-consensus membership change',
        'pre_vote': 'Pre-vote (term-inflation defense)',
        'raft_snapshots': 'Snapshots and log compaction',
        'linearizable_reads': 'Linearizable reads (ReadIndex/lease)',
        'multi_raft': 'Multi-Raft and sharding',
        'two_phase_commit': 'Distributed transactions / 2PC',
        'state_machine_replication': 'State machine replication',
    },
    {'02-raft-outline': ['raft_consensus', 'leader_election', 'replicated_log',
        'quorum_majority', 'joint_consensus', 'pre_vote', 'raft_snapshots',
        'linearizable_reads', 'multi_raft', 'two_phase_commit',
        'state_machine_replication']},
    [
        ('raft_consensus', 'leader_election', R, 0.95),
        ('raft_consensus', 'replicated_log', R, 0.95),
        ('raft_consensus', 'quorum_majority', R, 0.95),
        ('replicated_log', 'state_machine_replication', R, 0.95),
        ('leader_election', 'pre_vote', R, 0.95),
        ('raft_consensus', 'joint_consensus', R, 0.85),
        ('replicated_log', 'raft_snapshots', R, 0.85),
        ('linearizable_reads', 'quorum_majority', R, 0.85),
        ('multi_raft', 'raft_consensus', R, 0.85),
        ('raft_consensus', 'two_phase_commit', R, 0.65),
    ])

# ---- frontend / data-fetching ----
emit.emit_chunk('frontend', 'frontend',
    {
        'data_fetching': 'Data fetching strategy',
        'react_server_components': 'React Server Components',
        'suspense_streaming': 'Suspense boundaries and streaming',
        'swr_tanstack_query': 'Client cache (SWR / TanStack Query)',
        'request_waterfall': 'Request waterfalls',
        'optimistic_updates': 'Optimistic updates',
        'cache_invalidation': 'Cache invalidation and purging',
        'hydration_mismatch': 'Hydration mismatch',
        'lcp_metric': 'Largest Contentful Paint (LCP)',
        'fetch_race_conditions': 'Fetch race conditions',
        'server_functions': 'Server functions / action protocol',
    },
    {'02-data-fetching': ['data_fetching', 'react_server_components',
        'suspense_streaming', 'swr_tanstack_query', 'request_waterfall',
        'optimistic_updates', 'cache_invalidation', 'hydration_mismatch',
        'lcp_metric', 'fetch_race_conditions', 'server_functions']},
    [
        ('data_fetching', 'react_server_components', R, 0.95),
        ('data_fetching', 'request_waterfall', R, 0.95),
        ('react_server_components', 'suspense_streaming', R, 0.95),
        ('swr_tanstack_query', 'optimistic_updates', R, 0.95),
        ('swr_tanstack_query', 'cache_invalidation', R, 0.95),
        ('request_waterfall', 'lcp_metric', R, 0.85),
        ('data_fetching', 'hydration_mismatch', R, 0.65),
        ('optimistic_updates', 'fetch_race_conditions', R, 0.75),
        ('react_server_components', 'server_functions', R, 0.85),
    ])

# ---- queues / delivery-guarantees ----
emit.emit_chunk('queues', 'queues',
    {
        'delivery_guarantees': 'Delivery guarantees',
        'at_most_once': 'At-most-once delivery',
        'at_least_once_delivery': 'At-least-once delivery',
        'exactly_once_processing': 'Effectively-once processing',
        'two_generals_problem': 'Two Generals impossibility',
        'kafka_idempotent_producer': 'Kafka idempotent producer',
        'kafka_transactions': 'Kafka transactions',
        'consumer_dedup': 'Consumer-side deduplication',
        'sqs_visibility_timeout': 'SQS visibility timeout',
        'dlq_poison_message': 'Dead-letter queue / poison message',
        'outbox_pattern': 'Outbox pattern',
        'fifo_ordering': 'FIFO vs standard ordering',
        'consumer_groups': 'Consumer groups and rebalancing',
    },
    {'01-delivery-guarantees': ['delivery_guarantees', 'at_most_once',
        'at_least_once_delivery', 'exactly_once_processing', 'two_generals_problem',
        'kafka_idempotent_producer', 'kafka_transactions', 'consumer_dedup',
        'sqs_visibility_timeout', 'dlq_poison_message', 'outbox_pattern',
        'fifo_ordering', 'consumer_groups']},
    [
        ('delivery_guarantees', 'at_most_once', R, 0.95),
        ('delivery_guarantees', 'at_least_once_delivery', R, 0.95),
        ('delivery_guarantees', 'exactly_once_processing', R, 0.95),
        ('exactly_once_processing', 'two_generals_problem', R, 0.85),
        ('kafka_idempotent_producer', 'kafka_transactions', R, 0.95),
        ('exactly_once_processing', 'consumer_dedup', R, 0.95),
        ('at_least_once_delivery', 'sqs_visibility_timeout', R, 0.85),
        ('sqs_visibility_timeout', 'dlq_poison_message', R, 0.85),
        ('outbox_pattern', 'exactly_once_processing', R, 0.85),
        ('fifo_ordering', 'delivery_guarantees', R, 0.75),
        ('consumer_groups', 'fifo_ordering', R, 0.75),
    ])

# ---- security / oauth-oidc ----
emit.emit_chunk('security', 'security',
    {
        'oauth2': 'OAuth 2.1 framework',
        'oidc': 'OpenID Connect',
        'pkce_flow': 'Authorization code with PKCE',
        'refresh_token_rotation': 'Refresh token rotation',
        'id_token': 'OIDC ID token',
        'dpop_mtls_tokens': 'Sender-constrained tokens (DPoP/mTLS)',
        'jwks_validation': 'JWKS / JWT validation',
        'redirect_uri_match': 'Exact redirect_uri match',
        'scopes_least_privilege': 'Scopes and least privilege',
        'state_nonce': 'State and nonce anti-attack tokens',
        'jwt_pitfalls': 'JWT validation pitfalls',
        'token_theft_mitigation': 'Token theft mitigation',
    },
    {'02-oauth-oidc': ['oauth2', 'oidc', 'pkce_flow', 'refresh_token_rotation',
        'id_token', 'dpop_mtls_tokens', 'jwks_validation', 'redirect_uri_match',
        'scopes_least_privilege', 'state_nonce', 'jwt_pitfalls',
        'token_theft_mitigation']},
    [
        ('oauth2', 'pkce_flow', R, 0.95),
        ('oauth2', 'oidc', R, 0.95),
        ('oidc', 'id_token', R, 0.95),
        ('pkce_flow', 'redirect_uri_match', R, 0.95),
        ('pkce_flow', 'state_nonce', R, 0.85),
        ('refresh_token_rotation', 'token_theft_mitigation', R, 0.95),
        ('dpop_mtls_tokens', 'token_theft_mitigation', R, 0.95),
        ('id_token', 'jwks_validation', R, 0.85),
        ('jwks_validation', 'jwt_pitfalls', R, 0.95),
        ('oauth2', 'scopes_least_privilege', R, 0.85),
    ])
print('singletons done')
