import sys
sys.path.insert(0, 'graphify-out')
import relinear_emit as emit

concepts = {
    'speed_of_light_latency': 'Speed-of-light latency floor',
    'bandwidth_vs_latency': 'Bandwidth vs latency',
    'bandwidth_delay_product': 'Bandwidth-delay product (BDP)',
    'shannon_capacity': 'Shannon channel capacity',
    'physical_media_encoding': 'Physical media and signal encoding',
    'bufferbloat': 'Bufferbloat',
    'submarine_cable_backbone': 'Submarine cable backbone',
    'ip_packet_header': 'IP packet header',
    'longest_prefix_routing': 'Longest-prefix-match routing',
    'bgp_routing': 'BGP path-vector routing',
    'bgp_hijack_rpki': 'BGP hijack and RPKI',
    'nat_cgnat': 'NAT and CGNAT',
    'ipv6_dual_stack': 'IPv6 and dual-stack',
    'path_mtu_discovery': 'Path MTU Discovery and black holes',
    'ecmp_flow_hashing': 'ECMP flow hashing',
    'anycast_routing': 'Anycast routing',
    'ip_best_effort': 'Connectionless best-effort IP',
    'encapsulation': 'Protocol encapsulation',
    'tcp_three_way_handshake': 'TCP three-way handshake',
    'tcp_sequence_numbers': 'TCP sequence numbers and ISN',
    'tcp_flow_control': 'TCP sliding window and flow control',
    'tcp_congestion_control': 'TCP congestion control (CUBIC/BBR/Reno)',
    'tcp_loss_recovery': 'TCP loss detection and retransmission',
    'tcp_time_wait': 'TIME-WAIT exhaustion',
    'syn_flood_cookies': 'SYN flood and SYN cookies',
    'tcp_fast_open': 'TCP Fast Open',
    'nagle_delayed_ack': 'Nagle algorithm and delayed ACK',
    'explicit_congestion_notification': 'Explicit Congestion Notification (ECN)',
    'dns_resolution': 'DNS recursive resolution',
    'dns_caching_ttl': 'DNS caching and TTL',
    'dnssec': 'DNSSEC chain of trust',
    'encrypted_dns': 'Encrypted DNS (DoH/DoT/DoQ)',
    'dns_cache_poisoning': 'DNS cache poisoning (Kaminsky)',
    'tls13_handshake': 'TLS 1.3 one-RTT handshake',
    'perfect_forward_secrecy': 'Perfect Forward Secrecy',
    'zero_rtt_resumption': '0-RTT resumption and replay risk',
    'certificate_chain_validation': 'Certificate chain validation',
    'post_quantum_crypto': 'Post-quantum / hybrid key exchange',
    'encrypted_client_hello': 'Encrypted ClientHello (ECH)',
    'ktls_offload': 'Kernel TLS offload',
    'http_versions': 'HTTP/1.1 vs /2 vs /3',
    'http_multiplexing': 'HTTP stream multiplexing',
    'head_of_line_blocking': 'Head-of-line blocking',
    'http_caching_headers': 'HTTP caching headers',
    'cors': 'CORS cross-origin policy',
    'cookies_session_security': 'Cookies and session security',
    'quic_protocol': 'QUIC protocol',
    'connection_migration': 'QUIC connection migration',
    'quic_cpu_cost': 'QUIC CPU cost tradeoff',
    'cdn_edge_caching': 'CDN edge caching',
    'cache_invalidation': 'Cache invalidation and purging',
    'vary_header_caching': 'Vary header cache keying',
    'stale_while_revalidate': 'stale-while-revalidate',
    'edge_compute': 'Edge compute / workers',
    'cache_stampede': 'Cache stampede / thundering herd',
    'websocket_protocol': 'WebSocket full-duplex protocol',
    'backpressure': 'Backpressure and flow control',
    'connection_scaling': 'Connection scaling (C10K/C10M)',
    'reverse_proxy': 'Reverse proxy',
    'load_balancing_algorithms': 'Load balancing algorithms',
    'power_of_two_choices': 'Power-of-two-choices',
    'consistent_hashing': 'Consistent hashing',
    'health_checks': 'Health checks and outlier detection',
    'connection_draining': 'Connection draining and graceful shutdown',
    'circuit_breaker': 'Circuit breaker',
    'retry_storm': 'Retry storms and retry budgets',
    'l3_l4_l7_layering': 'L3/L4/L7 layering',
    'ddos_defense': 'DDoS defense-in-depth',
    'rate_limiting': 'Rate limiting (token bucket)',
    'amplification_reflection': 'Amplification and reflection attacks',
    'mtls': 'mTLS service identity',
    'web_application_firewall': 'Web Application Firewall',
    'ip_spoofing_bcp38': 'IP spoofing and BCP 38',
    'distributed_tracing': 'Distributed tracing (W3C Trace Context)',
    'red_use_method': 'RED/USE method metrics',
    'error_budget': 'Error budgets',
    'critical_render_path': 'Critical render path',
    'core_web_vitals': 'Core Web Vitals',
}

piece_concepts = {
    '01-physical-link': ['speed_of_light_latency', 'bandwidth_vs_latency',
        'bandwidth_delay_product', 'shannon_capacity', 'physical_media_encoding',
        'bufferbloat', 'submarine_cable_backbone', 'tcp_congestion_control'],
    '02-ip-packet': ['ip_packet_header', 'longest_prefix_routing', 'bgp_routing',
        'bgp_hijack_rpki', 'nat_cgnat', 'ipv6_dual_stack', 'path_mtu_discovery',
        'ecmp_flow_hashing', 'anycast_routing', 'ip_best_effort', 'encapsulation',
        'l3_l4_l7_layering', 'explicit_congestion_notification', 'ip_spoofing_bcp38'],
    '03-tcp-handshake': ['tcp_three_way_handshake', 'tcp_sequence_numbers',
        'tcp_flow_control', 'tcp_congestion_control', 'tcp_loss_recovery',
        'tcp_time_wait', 'syn_flood_cookies', 'tcp_fast_open', 'nagle_delayed_ack',
        'explicit_congestion_notification', 'bufferbloat', 'encapsulation'],
    '04-dns-resolution': ['dns_resolution', 'dns_caching_ttl', 'dnssec',
        'encrypted_dns', 'dns_cache_poisoning', 'anycast_routing',
        'encrypted_client_hello'],
    '05-tls-handshake': ['tls13_handshake', 'perfect_forward_secrecy',
        'zero_rtt_resumption', 'certificate_chain_validation', 'post_quantum_crypto',
        'encrypted_client_hello', 'ktls_offload', 'mtls'],
    '06-http-versions': ['http_versions', 'http_multiplexing', 'head_of_line_blocking',
        'http_caching_headers', 'cors', 'cookies_session_security', 'quic_protocol',
        'zero_rtt_resumption', 'rate_limiting'],
    '07-cdn-edge': ['cdn_edge_caching', 'cache_invalidation', 'vary_header_caching',
        'stale_while_revalidate', 'edge_compute', 'cache_stampede', 'anycast_routing',
        'http_caching_headers', 'web_application_firewall', 'core_web_vitals'],
    '08-websocket-realtime': ['websocket_protocol', 'backpressure', 'connection_scaling',
        'head_of_line_blocking', 'retry_storm'],
    '09-proxy-load-balancing': ['reverse_proxy', 'load_balancing_algorithms',
        'power_of_two_choices', 'consistent_hashing', 'health_checks',
        'connection_draining', 'circuit_breaker', 'retry_storm', 'l3_l4_l7_layering'],
    '10-quic-internals': ['quic_protocol', 'connection_migration', 'quic_cpu_cost',
        'head_of_line_blocking', 'tls13_handshake', 'zero_rtt_resumption',
        'tcp_congestion_control', 'tcp_loss_recovery'],
    '11-network-security': ['ddos_defense', 'rate_limiting', 'amplification_reflection',
        'mtls', 'web_application_firewall', 'syn_flood_cookies', 'bgp_hijack_rpki',
        'dns_cache_poisoning', 'ip_spoofing_bcp38', 'anycast_routing'],
    '12-putting-it-together': ['distributed_tracing', 'red_use_method', 'error_budget',
        'critical_render_path', 'core_web_vitals', 'circuit_breaker', 'retry_storm',
        'connection_migration', 'cdn_edge_caching', 'zero_rtt_resumption',
        'encrypted_client_hello'],
}

R = 'conceptually_related_to'
S = 'semantically_similar_to'
relations = [
    ('speed_of_light_latency', 'bandwidth_vs_latency', R, 0.95),
    ('bandwidth_delay_product', 'tcp_flow_control', R, 0.95),
    ('bandwidth_delay_product', 'tcp_congestion_control', R, 0.85),
    ('bufferbloat', 'tcp_congestion_control', R, 0.85),
    ('ip_packet_header', 'encapsulation', R, 0.85),
    ('longest_prefix_routing', 'bgp_routing', R, 0.95),
    ('bgp_routing', 'bgp_hijack_rpki', R, 0.95),
    ('bgp_hijack_rpki', 'ip_spoofing_bcp38', R, 0.75),
    ('anycast_routing', 'cdn_edge_caching', R, 0.85),
    ('anycast_routing', 'ddos_defense', R, 0.75),
    ('path_mtu_discovery', 'physical_media_encoding', R, 0.65),
    ('tcp_three_way_handshake', 'tcp_sequence_numbers', R, 0.95),
    ('tcp_three_way_handshake', 'tls13_handshake', R, 0.85),
    ('tcp_congestion_control', 'explicit_congestion_notification', R, 0.85),
    ('syn_flood_cookies', 'ddos_defense', R, 0.85),
    ('tcp_fast_open', 'zero_rtt_resumption', S, 0.85),
    ('dns_resolution', 'dns_caching_ttl', R, 0.95),
    ('dns_caching_ttl', 'cache_invalidation', S, 0.75),
    ('dnssec', 'dns_cache_poisoning', R, 0.95),
    ('encrypted_dns', 'encrypted_client_hello', R, 0.85),
    ('tls13_handshake', 'perfect_forward_secrecy', R, 0.95),
    ('tls13_handshake', 'zero_rtt_resumption', R, 0.95),
    ('zero_rtt_resumption', 'speed_of_light_latency', R, 0.65),
    ('certificate_chain_validation', 'mtls', R, 0.85),
    ('http_versions', 'http_multiplexing', R, 0.95),
    ('http_multiplexing', 'head_of_line_blocking', R, 0.95),
    ('head_of_line_blocking', 'quic_protocol', R, 0.95),
    ('quic_protocol', 'tls13_handshake', R, 0.85),
    ('quic_protocol', 'connection_migration', R, 0.95),
    ('quic_cpu_cost', 'ktls_offload', R, 0.65),
    ('cdn_edge_caching', 'cache_invalidation', R, 0.95),
    ('cache_invalidation', 'vary_header_caching', R, 0.85),
    ('vary_header_caching', 'http_caching_headers', R, 0.85),
    ('stale_while_revalidate', 'cache_stampede', R, 0.85),
    ('edge_compute', 'cdn_edge_caching', R, 0.85),
    ('websocket_protocol', 'backpressure', R, 0.95),
    ('connection_scaling', 'backpressure', R, 0.85),
    ('reverse_proxy', 'load_balancing_algorithms', R, 0.95),
    ('load_balancing_algorithms', 'power_of_two_choices', R, 0.95),
    ('load_balancing_algorithms', 'consistent_hashing', R, 0.85),
    ('health_checks', 'circuit_breaker', R, 0.85),
    ('circuit_breaker', 'retry_storm', R, 0.95),
    ('connection_draining', 'health_checks', R, 0.75),
    ('ddos_defense', 'rate_limiting', R, 0.95),
    ('rate_limiting', 'amplification_reflection', R, 0.75),
    ('amplification_reflection', 'ip_spoofing_bcp38', R, 0.85),
    ('web_application_firewall', 'ddos_defense', R, 0.85),
    ('distributed_tracing', 'red_use_method', R, 0.85),
    ('red_use_method', 'error_budget', R, 0.85),
    ('critical_render_path', 'core_web_vitals', R, 0.95),
    ('core_web_vitals', 'cdn_edge_caching', R, 0.65),
]

emit.emit_chunk('networking', 'networking', concepts, piece_concepts, relations)
