import sys
sys.path.insert(0, 'graphify-out')
import relinear_emit as emit

concepts = {
    'profiling': 'Profiling',
    'amdahls_law': "Amdahl's law",
    'measurement_loop': 'Measurement loop',
    'wall_cpu_self_time': 'Wall-clock vs CPU vs self-time',
    'microbenchmark_pitfalls': 'Microbenchmark pitfalls',
    'observer_effect': 'Observer effect',
    'flame_graph': 'Flame graph',
    'continuous_profiling': 'Continuous profiling',
    'profile_ci_gate': 'Profile-driven CI gates',
    'hardware_perf_counters': 'Hardware performance counters',
    'hot_path_classification': 'Hot-path classification',
    'cpu_bound': 'CPU-bound hot path',
    'allocation_bound': 'Allocation-bound hot path',
    'cache_bound': 'Cache-bound hot path',
    'lock_bound': 'Lock-bound hot path',
    'syscall_bound': 'Syscall-bound hot path',
    'intel_tma': 'Intel Top-down Microarchitecture Analysis',
    'deoptimization': 'JIT deoptimization',
    'false_sharing': 'False sharing / cache-coherency contention',
    'fix_verify_loop': 'Fix-and-verify loop',
    'cache_hierarchy': 'CPU cache hierarchy',
    'cache_lines': 'Cache lines',
    'data_locality': 'Data locality and layout',
    'branch_prediction': 'Branch prediction',
    'branchless_code': 'Branchless code',
    'simd_vectorization': 'SIMD and vectorization',
    'numa': 'NUMA multi-socket effects',
    'memory_bandwidth': 'Memory bandwidth limits',
    'hardware_prefetcher': 'Hardware prefetcher',
    'cache_oblivious_algorithms': 'Cache-oblivious algorithms',
    'big_o_vs_reality': 'Big-O vs cache reality',
    'garbage_collection': 'Garbage collection',
    'mark_and_sweep': 'Mark and sweep',
    'generational_gc': 'Generational GC',
    'concurrent_gc': 'Concurrent / incremental GC',
    'gc_three_way_tradeoff': 'GC pause/throughput/heap tradeoff',
    'allocation_pressure': 'Allocation pressure',
    'tricolor_marking': 'Tri-color marking and write barrier',
    'zgc_colored_pointers': 'ZGC colored pointers',
    'object_pooling': 'Object pooling',
    'orinoco_gc': 'Orinoco concurrent GC',
    'n_plus_one': 'N+1 query problem',
    'orm_lazy_loading': 'ORM lazy loading',
    'join_fix': 'JOIN / IN fix patterns',
    'dataloader_batching': 'DataLoader batch loader',
    'eager_loading': 'Eager loading / preload',
    'query_amplification_dos': 'Query amplification as DoS',
    'microservice_fan_out': 'Microservice synchronous fan-out',
    'connection_pooling': 'Connection pooling',
    'batching': 'Batching',
    'batch_window': 'Batch size/time window',
    'fixed_cost_amortization': 'Fixed-cost amortization',
    'kafka_producer_batching': 'Kafka producer batching',
    'bulk_insert': 'Database bulk insert',
    'io_uring': 'io_uring syscall batching',
    'adaptive_batching': 'Adaptive batching',
    'poison_pill': 'Poison pill / batch failure isolation',
    'pipelining_vs_batching': 'Pipelining vs batching',
    'nagle_delayed_ack': 'Nagle algorithm and delayed ACK',
    'backpressure': 'Backpressure and bounded queues',
    'head_of_line_blocking': 'Head-of-line blocking',
    'bundle_budgets': 'JS bundle budgets',
    'js_parse_compile_cost': 'JS parse/compile/execute cost',
    'code_splitting': 'Code splitting',
    'tree_shaking': 'Tree shaking / dead code elimination',
    'compression_gzip_brotli': 'gzip vs brotli compression',
    'third_party_scripts': 'Third-party script cost',
    'mobile_cpu_gap': 'Mobile CPU gap',
    'resource_hints': 'Resource hints (preload/prefetch)',
    'core_web_vitals': 'Core Web Vitals',
    'v8_jit_tiers': 'V8 tiered JIT pipeline',
    'lighthouse_rum': 'Lighthouse vs RUM',
    'performance_loop': 'Performance discipline loop',
    'performance_culture': 'Performance-first culture',
    'premerge_perf_gates': 'Pre-merge performance gates',
    'performance_economics': 'Economics of performance',
    'capacity_planning': 'Capacity planning',
    'error_budget': 'Error budgets',
    'slo': 'Service Level Objective (SLO)',
    'red_use_method': 'RED/USE method metrics',
    'opentelemetry': 'OpenTelemetry',
}

piece_concepts = {
    '01-profile-first': ['profiling', 'amdahls_law', 'measurement_loop',
        'wall_cpu_self_time', 'microbenchmark_pitfalls', 'observer_effect',
        'flame_graph', 'continuous_profiling', 'profile_ci_gate',
        'hardware_perf_counters'],
    '02-hot-paths': ['hot_path_classification', 'cpu_bound', 'allocation_bound',
        'cache_bound', 'lock_bound', 'syscall_bound', 'intel_tma', 'deoptimization',
        'false_sharing', 'fix_verify_loop'],
    '03-cache-vs-bigo': ['cache_hierarchy', 'cache_lines', 'data_locality',
        'branch_prediction', 'branchless_code', 'simd_vectorization', 'numa',
        'memory_bandwidth', 'hardware_prefetcher', 'cache_oblivious_algorithms',
        'big_o_vs_reality'],
    '04-gc': ['garbage_collection', 'mark_and_sweep', 'generational_gc',
        'concurrent_gc', 'gc_three_way_tradeoff', 'allocation_pressure',
        'tricolor_marking', 'zgc_colored_pointers', 'object_pooling', 'orinoco_gc'],
    '05-n-plus-one': ['n_plus_one', 'orm_lazy_loading', 'join_fix',
        'dataloader_batching', 'eager_loading', 'query_amplification_dos',
        'microservice_fan_out', 'connection_pooling'],
    '06-batching': ['batching', 'batch_window', 'fixed_cost_amortization',
        'kafka_producer_batching', 'bulk_insert', 'io_uring', 'adaptive_batching',
        'poison_pill', 'pipelining_vs_batching', 'nagle_delayed_ack', 'backpressure',
        'head_of_line_blocking'],
    '07-bundle-budgets': ['bundle_budgets', 'js_parse_compile_cost', 'code_splitting',
        'tree_shaking', 'compression_gzip_brotli', 'third_party_scripts',
        'mobile_cpu_gap', 'resource_hints', 'core_web_vitals', 'v8_jit_tiers',
        'lighthouse_rum'],
    '08-putting-it-together': ['performance_loop', 'performance_culture',
        'premerge_perf_gates', 'performance_economics', 'capacity_planning',
        'error_budget', 'slo', 'red_use_method', 'opentelemetry', 'profiling'],
}

R = 'conceptually_related_to'
S = 'semantically_similar_to'
relations = [
    ('profiling', 'amdahls_law', R, 0.85),
    ('profiling', 'flame_graph', R, 0.95),
    ('profiling', 'measurement_loop', R, 0.95),
    ('measurement_loop', 'fix_verify_loop', R, 0.85),
    ('microbenchmark_pitfalls', 'observer_effect', R, 0.85),
    ('profiling', 'continuous_profiling', R, 0.95),
    ('profile_ci_gate', 'premerge_perf_gates', S, 0.85),
    ('hardware_perf_counters', 'intel_tma', R, 0.85),
    ('hot_path_classification', 'cpu_bound', R, 0.95),
    ('hot_path_classification', 'allocation_bound', R, 0.95),
    ('hot_path_classification', 'cache_bound', R, 0.95),
    ('hot_path_classification', 'lock_bound', R, 0.95),
    ('hot_path_classification', 'syscall_bound', R, 0.95),
    ('hot_path_classification', 'flame_graph', R, 0.85),
    ('intel_tma', 'hot_path_classification', R, 0.85),
    ('cpu_bound', 'deoptimization', R, 0.75),
    ('lock_bound', 'false_sharing', R, 0.85),
    ('allocation_bound', 'allocation_pressure', R, 0.95),
    ('cache_bound', 'cache_hierarchy', R, 0.95),
    ('cache_hierarchy', 'cache_lines', R, 0.95),
    ('cache_lines', 'data_locality', R, 0.95),
    ('data_locality', 'big_o_vs_reality', R, 0.95),
    ('branch_prediction', 'branchless_code', R, 0.95),
    ('simd_vectorization', 'data_locality', R, 0.85),
    ('numa', 'memory_bandwidth', R, 0.85),
    ('hardware_prefetcher', 'cache_lines', R, 0.85),
    ('cache_oblivious_algorithms', 'data_locality', R, 0.85),
    ('false_sharing', 'cache_lines', R, 0.85),
    ('garbage_collection', 'mark_and_sweep', R, 0.95),
    ('garbage_collection', 'generational_gc', R, 0.95),
    ('garbage_collection', 'concurrent_gc', R, 0.95),
    ('garbage_collection', 'gc_three_way_tradeoff', R, 0.95),
    ('allocation_pressure', 'gc_three_way_tradeoff', R, 0.85),
    ('concurrent_gc', 'tricolor_marking', R, 0.95),
    ('concurrent_gc', 'zgc_colored_pointers', R, 0.85),
    ('garbage_collection', 'orinoco_gc', R, 0.85),
    ('object_pooling', 'allocation_pressure', R, 0.85),
    ('n_plus_one', 'orm_lazy_loading', R, 0.95),
    ('n_plus_one', 'join_fix', R, 0.95),
    ('n_plus_one', 'dataloader_batching', R, 0.95),
    ('n_plus_one', 'eager_loading', R, 0.95),
    ('dataloader_batching', 'batching', R, 0.85),
    ('n_plus_one', 'microservice_fan_out', R, 0.85),
    ('n_plus_one', 'connection_pooling', R, 0.65),
    ('query_amplification_dos', 'n_plus_one', R, 0.75),
    ('batching', 'batch_window', R, 0.95),
    ('batching', 'fixed_cost_amortization', R, 0.95),
    ('batching', 'kafka_producer_batching', R, 0.85),
    ('batching', 'bulk_insert', R, 0.85),
    ('batching', 'io_uring', R, 0.85),
    ('batching', 'adaptive_batching', R, 0.95),
    ('batching', 'pipelining_vs_batching', R, 0.85),
    ('batch_window', 'nagle_delayed_ack', R, 0.85),
    ('poison_pill', 'backpressure', R, 0.75),
    ('batching', 'head_of_line_blocking', R, 0.65),
    ('bundle_budgets', 'js_parse_compile_cost', R, 0.95),
    ('bundle_budgets', 'code_splitting', R, 0.95),
    ('bundle_budgets', 'tree_shaking', R, 0.95),
    ('bundle_budgets', 'compression_gzip_brotli', R, 0.85),
    ('third_party_scripts', 'bundle_budgets', R, 0.85),
    ('js_parse_compile_cost', 'v8_jit_tiers', R, 0.85),
    ('js_parse_compile_cost', 'mobile_cpu_gap', R, 0.85),
    ('bundle_budgets', 'core_web_vitals', R, 0.85),
    ('resource_hints', 'code_splitting', R, 0.75),
    ('lighthouse_rum', 'core_web_vitals', R, 0.85),
    ('performance_loop', 'performance_culture', R, 0.95),
    ('performance_loop', 'fix_verify_loop', R, 0.85),
    ('premerge_perf_gates', 'performance_loop', R, 0.85),
    ('performance_loop', 'slo', R, 0.85),
    ('slo', 'error_budget', R, 0.95),
    ('performance_loop', 'red_use_method', R, 0.75),
    ('capacity_planning', 'performance_economics', R, 0.75),
]

emit.emit_chunk('performance', 'performance', concepts, piece_concepts, relations)
