import sys
sys.path.insert(0, 'graphify-out')
import relinear_emit as emit

concepts = {
    'event_loop': 'Browser event loop',
    'task_microtask_queues': 'Tasks vs microtasks',
    'render_step': 'Render step in the loop',
    'scheduler_yield': 'scheduler.yield() and postTask',
    'long_tasks_inp': 'Long tasks and the 50ms cap',
    'request_animation_frame': 'requestAnimationFrame timing',
    'node_event_loop': 'Node.js event loop phases',
    'framework_scheduler': 'React/Vue framework schedulers',
    'render_pipeline': 'Browser render pipeline',
    'cssom_layout_paint': 'CSSOM, layout, paint, composite',
    'main_thread_bottleneck': 'Main-thread bottleneck',
    'compositor_thread': 'Compositor thread and layers',
    'layout_thrash': 'Forced synchronous layout (thrash)',
    'composite_only_animation': 'Composite-only animations',
    'layer_promotion': 'Compositor layer promotion',
    'render_invalidation': 'Render invalidation propagation',
    'content_visibility': 'content-visibility and contain',
    'v8_jit_tiers': 'V8 tiered JIT pipeline',
    'hidden_classes': 'Hidden classes / shapes',
    'inline_caches': 'Inline caches',
    'deoptimization': 'JIT deoptimization',
    'orinoco_gc': 'Orinoco concurrent GC',
    'polymorphism_megamorphic': 'Polymorphism and megamorphic ICs',
    'v8_isolates': 'V8 isolates (tenant isolation)',
    'incremental_marking': 'Incremental marking and write barriers',
    'web_workers': 'Web workers (off-main-thread compute)',
    'service_workers': 'Service workers (network proxy)',
    'worklets': 'Worklets (render-thread hooks)',
    'shared_array_buffer': 'SharedArrayBuffer and Atomics',
    'structured_clone': 'Structured clone / postMessage cost',
    'coop_coep': 'COOP/COEP cross-origin isolation',
    'worker_cache_strategies': 'Service-worker cache strategies',
    'offscreen_canvas': 'OffscreenCanvas',
    'react_fiber': 'React Fiber reconciler',
    'render_commit_phases': 'Render vs commit phase',
    'reconciliation_diffing': 'Reconciliation diffing rules',
    'react_keys': 'React keys and identity',
    'priority_lanes': 'React priority lanes',
    'time_slicing': 'Time-slicing (5ms)',
    'use_transition': 'useTransition / useDeferredValue',
    'virtual_dom': 'Virtual DOM',
    'render_strategies': 'Render strategies (SSR/SSG/ISR/streaming)',
    'hydration': 'Hydration',
    'react_server_components': 'React Server Components',
    'islands_architecture': 'Islands architecture',
    'progressive_hydration': 'Progressive / selective hydration',
    'resumability': 'Resumability',
    'hydration_mismatch': 'Hydration mismatch',
    'streaming_ssr': 'Streaming SSR',
    'core_web_vitals': 'Core Web Vitals',
    'lcp_metric': 'Largest Contentful Paint (LCP)',
    'inp_metric': 'Interaction to Next Paint (INP)',
    'cls_metric': 'Cumulative Layout Shift (CLS)',
    'lab_vs_field': 'Lab vs field measurement',
    'rum_monitoring': 'Real-User Monitoring (RUM)',
    'preload_scanner': 'Preload scanner',
    'ttfb_fcp': 'TTFB and FCP supporting metrics',
    'page_load_trace': 'End-to-end page-load trace',
    'uncanny_valley_interactivity': 'Painted-but-not-interactive valley',
    'devtools_performance_trace': 'DevTools performance trace',
}

piece_concepts = {
    '01-event-loop': ['event_loop', 'task_microtask_queues', 'render_step',
        'scheduler_yield', 'long_tasks_inp', 'request_animation_frame',
        'node_event_loop', 'framework_scheduler'],
    '02-render-pipeline': ['render_pipeline', 'cssom_layout_paint',
        'main_thread_bottleneck', 'compositor_thread', 'layout_thrash',
        'composite_only_animation', 'layer_promotion', 'render_invalidation',
        'content_visibility'],
    '03-v8-internals': ['v8_jit_tiers', 'hidden_classes', 'inline_caches',
        'deoptimization', 'orinoco_gc', 'polymorphism_megamorphic', 'v8_isolates',
        'incremental_marking'],
    '04-workers': ['web_workers', 'service_workers', 'worklets', 'shared_array_buffer',
        'structured_clone', 'coop_coep', 'worker_cache_strategies', 'offscreen_canvas'],
    '05-react-fiber': ['react_fiber', 'render_commit_phases', 'reconciliation_diffing',
        'react_keys', 'priority_lanes', 'time_slicing', 'use_transition', 'virtual_dom'],
    '06-ssr-vs-ssg': ['render_strategies', 'hydration', 'react_server_components',
        'islands_architecture', 'progressive_hydration', 'resumability',
        'hydration_mismatch', 'streaming_ssr'],
    '07-core-web-vitals': ['core_web_vitals', 'lcp_metric', 'inp_metric', 'cls_metric',
        'lab_vs_field', 'rum_monitoring', 'preload_scanner', 'ttfb_fcp'],
    '08-putting-it-together': ['page_load_trace', 'uncanny_valley_interactivity',
        'devtools_performance_trace', 'hydration', 'core_web_vitals', 'v8_jit_tiers',
        'render_pipeline', 'service_workers', 'react_fiber'],
}

R = 'conceptually_related_to'
S = 'semantically_similar_to'
relations = [
    ('event_loop', 'task_microtask_queues', R, 0.95),
    ('event_loop', 'render_step', R, 0.95),
    ('long_tasks_inp', 'scheduler_yield', R, 0.95),
    ('long_tasks_inp', 'inp_metric', R, 0.95),
    ('event_loop', 'node_event_loop', S, 0.85),
    ('framework_scheduler', 'react_fiber', R, 0.85),
    ('request_animation_frame', 'render_step', R, 0.85),
    ('render_pipeline', 'cssom_layout_paint', R, 0.95),
    ('render_pipeline', 'render_step', R, 0.85),
    ('main_thread_bottleneck', 'compositor_thread', R, 0.95),
    ('layout_thrash', 'render_invalidation', R, 0.95),
    ('composite_only_animation', 'layer_promotion', R, 0.95),
    ('composite_only_animation', 'compositor_thread', R, 0.85),
    ('content_visibility', 'render_invalidation', R, 0.75),
    ('v8_jit_tiers', 'hidden_classes', R, 0.95),
    ('hidden_classes', 'inline_caches', R, 0.95),
    ('inline_caches', 'polymorphism_megamorphic', R, 0.95),
    ('polymorphism_megamorphic', 'deoptimization', R, 0.95),
    ('orinoco_gc', 'incremental_marking', R, 0.95),
    ('v8_isolates', 'web_workers', R, 0.65),
    ('web_workers', 'structured_clone', R, 0.95),
    ('web_workers', 'shared_array_buffer', R, 0.85),
    ('shared_array_buffer', 'coop_coep', R, 0.95),
    ('service_workers', 'worker_cache_strategies', R, 0.95),
    ('worklets', 'compositor_thread', R, 0.65),
    ('web_workers', 'main_thread_bottleneck', R, 0.85),
    ('react_fiber', 'render_commit_phases', R, 0.95),
    ('react_fiber', 'reconciliation_diffing', R, 0.95),
    ('reconciliation_diffing', 'react_keys', R, 0.95),
    ('react_fiber', 'virtual_dom', R, 0.85),
    ('priority_lanes', 'time_slicing', R, 0.95),
    ('time_slicing', 'use_transition', R, 0.95),
    ('time_slicing', 'long_tasks_inp', R, 0.75),
    ('render_strategies', 'hydration', R, 0.95),
    ('hydration', 'react_server_components', R, 0.85),
    ('hydration', 'islands_architecture', R, 0.95),
    ('islands_architecture', 'progressive_hydration', R, 0.95),
    ('progressive_hydration', 'resumability', R, 0.85),
    ('hydration', 'hydration_mismatch', R, 0.95),
    ('streaming_ssr', 'render_strategies', R, 0.95),
    ('hydration', 'inp_metric', R, 0.85),
    ('hydration_mismatch', 'cls_metric', R, 0.75),
    ('core_web_vitals', 'lcp_metric', R, 0.95),
    ('core_web_vitals', 'inp_metric', R, 0.95),
    ('core_web_vitals', 'cls_metric', R, 0.95),
    ('lcp_metric', 'preload_scanner', R, 0.85),
    ('lab_vs_field', 'rum_monitoring', R, 0.95),
    ('ttfb_fcp', 'lcp_metric', R, 0.85),
    ('page_load_trace', 'devtools_performance_trace', R, 0.95),
    ('uncanny_valley_interactivity', 'hydration', R, 0.95),
    ('page_load_trace', 'core_web_vitals', R, 0.85),
]

emit.emit_chunk('browser', 'browser', concepts, piece_concepts, relations)
