// site/src/english/placement/sample-words.ts
// Stratified real-word sample for the vocab-size placement test. lemma/rank are
// taken verbatim from ngsl.csv / nawl.csv (CC BY-SA 4.0). ~50 words across bands.
import type { Band } from "~/english/types";

export type SampleWord = { lemma: string; rank: number; band: Band };

export const SAMPLE_WORDS: SampleWord[] = [
  { lemma: "say", rank: 30, band: "A2" },
  { lemma: "way", rank: 80, band: "A2" },
  { lemma: "part", rank: 130, band: "A2" },
  { lemma: "every", rank: 180, band: "A2" },
  { lemma: "increase", rank: 230, band: "A2" },
  { lemma: "term", rank: 280, band: "A2" },
  { lemma: "past", rank: 330, band: "A2" },
  { lemma: "reach", rank: 380, band: "A2" },
  { lemma: "situation", rank: 430, band: "A2" },
  { lemma: "themselves", rank: 480, band: "A2" },
  { lemma: "industry", rank: 530, band: "A2" },
  { lemma: "check", rank: 580, band: "A2" },
  { lemma: "article", rank: 630, band: "A2" },
  { lemma: "influence", rank: 680, band: "A2" },
  { lemma: "review", rank: 730, band: "A2" },
  { lemma: "unit", rank: 780, band: "A2" },
  { lemma: "energy", rank: 830, band: "B1" },
  { lemma: "disease", rank: 905, band: "B1" },
  { lemma: "conversation", rank: 980, band: "B1" },
  { lemma: "title", rank: 1055, band: "B1" },
  { lemma: "warn", rank: 1130, band: "B1" },
  { lemma: "senior", rank: 1205, band: "B1" },
  { lemma: "initial", rank: 1280, band: "B1" },
  { lemma: "cancer", rank: 1355, band: "B1" },
  { lemma: "bedroom", rank: 1430, band: "B1" },
  { lemma: "commitment", rank: 1505, band: "B1" },
  { lemma: "characteristic", rank: 1580, band: "B1" },
  { lemma: "chemical", rank: 1655, band: "B1" },
  { lemma: "multiple", rank: 1730, band: "B1" },
  { lemma: "incident", rank: 1805, band: "B1" },
  { lemma: "dish", rank: 1880, band: "B1" },
  { lemma: "convention", rank: 1955, band: "B1" },
  { lemma: "slight", rank: 2040, band: "B2" },
  { lemma: "obligation", rank: 2135, band: "B2" },
  { lemma: "interpret", rank: 2230, band: "B2" },
  { lemma: "exact", rank: 2325, band: "B2" },
  { lemma: "evolution", rank: 2420, band: "B2" },
  { lemma: "pile", rank: 2515, band: "B2" },
  { lemma: "racial", rank: 2610, band: "B2" },
  { lemma: "universe", rank: 2705, band: "B2" },
  { lemma: "found", rank: 2800, band: "B2" },
  { lemma: "lifetime", rank: 50, band: "B2" },
  { lemma: "initiate", rank: 150, band: "B2" },
  { lemma: "legend", rank: 250, band: "B2" },
  { lemma: "minimal", rank: 350, band: "B2" },
  { lemma: "mathematical", rank: 450, band: "B2" },
  { lemma: "disturbance", rank: 550, band: "B2" },
  { lemma: "mobility", rank: 650, band: "B2" },
  { lemma: "realism", rank: 750, band: "B2" },
  { lemma: "facet", rank: 850, band: "B2" },
];
